# Generated by Django 5.0.2 on 2024-02-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentrate',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
