# Generated by Django 5.0.2 on 2024-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_currentrate_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('fullname', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='WebsiteLogo')),
                ('max', models.CharField(max_length=1000)),
                ('min', models.CharField(max_length=1000)),
                ('sendby', models.CharField(max_length=1000)),
                ('receiveby', models.CharField(max_length=1000)),
                ('security', models.CharField(max_length=1000)),
                ('support', models.CharField(max_length=1000)),
                ('offer', models.CharField(max_length=1000)),
                ('sendmoneyprocess', models.TextField()),
                ('fullreviewlink', models.CharField(max_length=1000)),
            ],
        ),
    ]
