# Generated by Django 5.0.2 on 2024-02-17 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_websitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelist',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websitelist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
