# Generated by Django 5.0.2 on 2024-02-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_websitelist_title_alter_websitelist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsAndRatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('datetime', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.websitelist')),
            ],
        ),
    ]
