# Generated by Django 5.0.2 on 2024-02-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_reviewsandratting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelist',
            name='sendUrl',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
